application: TenantryNet
version: 1.1
runtime: python
api_version: 1

handlers:
- url: /css
  static_dir: stylesheets

- url: /img
  static_dir: img

- url: /css
  static_dir: css  

- url: /.*
  script: main.py
  
- url: /tasks
  script: tasks.py